#!/usr/bin/env bash
# This is installing the load balancer

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 191779-web-01 35.153.19.187:80 check
    server 191779-web-02 52.3.246.17:80 check
"
# This Updates packages
apt-get -y update
apt-get -y upgrade

# This Adds HAProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

# This installs HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
