#!/usr/bin/env bash
# Displays "To infinity and beyond" with
#+ a sleep 2 in between every iteration.
#   Displays "I am invincible!!!" in between every iteration.

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
